### PR TITLE
Add linter and apply fixes

### PR DESCRIPTION
**Pull request by tiago154**
Hello.

This PR, adds some items as per issue #4.

* Eslint configuration
* .editorConfig
* lint related scripts
* pre-commit using lint script

Some changes were also applied due to lint errors.

Any problem I am available.

### CODE REVIEW

**Comment by capJavert** [comment]
@tiago154 thanks for your contribution, I'll get on reviewing this next week. Added `hacktoberfest-accepted` label because the changes seem ok by glancing at them. 🤘

**Review by capJavert — CHANGES_REQUESTED** [review]
When I try to commit something I get:
```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

This is due to invalid permissions. 

I think you need to delete current `.husky/pre-commit` file and create it again with `npx husky add`. Check usage page https://github.com/typicode/husky#usage

After that the above warning should be gone because `add` command will add proper permissions to the file. Also you should be able to make a commit without the above warnings.

Everything else looks 👍

**Comment by tiago154** [comment]
> hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.

Hello @capJavert .

I made the change following your tip. Can you please validate if everything is ok now?

**Review by capJavert — CHANGES_REQUESTED** [review]
Permissions are still not valid, yours has:
```
$ ls -al .husky/
-rw-r--r--   1 javert  staff   55 Oct 21 11:46 pre-commit
```

and it should be:
```
$ ls -al .husky/
-rwxr-xr-x   1 javert  staff   55 Oct 21 11:46 pre-commit
```

You can add me to your fork so I can commit the right version If you are having problems.

**Comment by tiago154** [comment]
> Permissions are still not valid, yours has:
> 
> ```
> $ ls -al .husky/
> -rw-r--r--   1 javert  staff   55 Oct 21 11:46 pre-commit
> ```
> 
> and it should be:
> 
> ```
> $ ls -al .husky/
> -rwxr-xr-x   1 javert  staff   55 Oct 21 11:46 pre-commit
> ```
> 
> You can add me to your fork so I can commit the right version If you are having problems.

Hello @capJavert.

I believe the problem was caused by my being using Windows. I made new changes and validated now on a Linux too.

I think it worked now, so please check.

**Comment by capJavert** [comment]
Closes #14

**Comment by capJavert** [comment]
LGTM, thanks @tiago154

**Pull request merged**
